version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: task_management_db
    restart: no
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: task_management_redis
    restart: no
    ports:
      - "6379:6379"

volumes:
  postgres_data:
